### ISSUE TITLE
Double Checking Shield PCB Routing

### ISSUE THREAD

**Issue by Reyna-5970** [Agile-and-Adaptive-Robotics/Inverted_Pendulum#14]
![image](https://user-images.githubusercontent.com/55515949/87332163-0b5c1280-c4f0-11ea-8a18-19b11a445463.png)

I want to make sure that this will work -- and check-in to see if there are any changes you would make to the prototype. Once it's finalized, how does the ordering process work?

**Comment by jakechung42** [comment]
hmm, I have never done Arduino Shield PCB design before. Maybe @Scharzenberger might know something about this?

**Comment by Reyna-5970** [comment]
![image](https://user-images.githubusercontent.com/55515949/87335435-2aa96e80-c4f5-11ea-8808-d45b740329b5.png)

**Comment by Scharzenberger** [comment]
Hey Reyna,

I just looked over your PCB board.  Looks pretty good!  Here are a few notes / thoughts about what you have so far:

- @Conroy135 Can you confirm IMU wiring for us?  It looks like it could be right, but since you used them before, you will probably be able to tell immediately.

-If you aren't already doing this (looks like you are maybe?), you should make the bottom plane a ground plane.  I don't remember how off the top of my head, but you should make the bottom plane a ground plane (you should be able to figure out how by googling, since it is easy if I remember correctly).  This not only makes it very easy to connect things to ground, but also helps with noise, cooling, etc.  It is generally considered best practice to make one plane a ground plane in two layer boards and one plane a ground plane & one plane a power plane in four layer boards.

- Unfortunately, the valve manifold has a 26 pin connector, regardless as to how many pins you actually use...  So I would change the 4 pins you have representing the valve manifold to 26 pins (you have them labeled correctly, the extra ones would just be dummy pins).  This will let us easily plug the valve manifold in.

- Your transistor array looks correct in the schematic, but not on the board.  Not sure why this is, but check it out.  On the schematic, ground is on the same side as the valve manifold.  On the board, ground is on the other side for some reason?  Not sure what's going on there, but they should match.

- Just a thought for the encoder pins.  It would be very helpful to use screw terminals.  Something like this: [https://www.amazon.com/DIYhz-green-Terminal-Connector-Arduino/dp/B07B79Q911/ref=zg_bs_306731011_50?_encoding=UTF8&psc=1&refRID=3M66JXG2FXZTV3SJHGGR](https://www.amazon.com/DIYhz-green-Terminal-Connector-Arduino/dp/B07B79Q911/ref=zg_bs_306731011_50?_encoding=UTF8&psc=1&refRID=3M66JXG2FXZTV3SJHGGR).  That way we don't have to solder the encoder wires to the breadboard (and not have to unsolder them to replace them / fix issues).

- Where is your +24V connection?  We are going to need to plug it into the shield somewhere.  I would again suggest using a screw terminal (like above).  Have a +24V & GND pair.  Then take the +24V over to the transistor array.  It looks like the transistor array might currently be attached to +5V, which is not correct (despite the fact that it looks right on the schematic...?).  The +24V line will also need a bigger than usual trace.  You can look up what the rule is, but I think it is like 1mil per volt or something.  So it would be about 20mils wide?  (Double check, but I think that is about right).

Not a big deal, but here are some routing best practices to keep in mind (you have a relatively big board with relatively few components, so it is not as critical, but still a good idea):

- Use the smallest angle bends possible.  e.g., avoid 90 deg bends (use two 45 deg bends instead).

- Minimize non-ground lines on the bottom plane.  Put as many lines as possible in the top plane.

- Use as short of traces as possible.

- Minimize the use of vias.  Yes, this is in direct contradiction to the "use as short of traces as possible" goal.  You have to balance the two. I will generally prefer to use vias if it means that I can make the wiring shorter and more organized.

- Make the traces in each area go more or less in the same direction.  If you have to via to the bottom plane, try to pick a consistence direction to move in the bottom plane (e.g., up-down or left-right).

Overall, looks pretty good.  If you can figure out what is wrong with the transistor array, then the other stuff is more just quality of life improvements (not fatal).

Let me know if you have any questions.

Best Regards,

Cody

**Comment by Conroy135** [comment]
IMU connections look good! I haven't used a mega with an IMU so there might be some issues, but that will likely come from code complications.

**Comment by Scharzenberger** [comment]
Hey Connor,

Thanks for the feedback.  Do you remember the name of the library you were using to communication with the IMUs?

**Comment by Conroy135** [comment]
I used the various libraries from Adafruit. If you have a specific IMU, Adafruit likely has a good library to use for it. It will also need the wire.h library, which can be found in the Arduino IDE without any outside installation.

**Comment by Reyna-5970** [comment]
@Scharzenberger What's does the footprint of the valve manifold pins look like? Is it 2x13, 1x26... etc.? Also, it might just be easier to put the valve manifold off of the platform all together and just plug in the pins needed, because I imagine having the manifold directly mounted would dramatically alter the balance of the platform.

**Comment by Scharzenberger** [comment]
Hey Reyna,

The footprint for the valve manifold connector is 2x13 (standard pitch, whatever that is. :p).  I agree -- the valve manifold is pretty heavy, so that could screw things up.  Regardless as to whether the valve manifold is mounted to the platform, the easiest way to electrically connect it will still be to use the 2x13 connector.  The connectors it has lock it into place so it doesn't come unplugged.  If we just used wires, we would either have to solder to the manifold (which I wouldn't do, because the manifold is expensive and we would have to unsolder to remove it) or use the female jumper cables (which get unplugged very easily).

**Comment by Reyna-5970** [comment]
![image](https://user-images.githubusercontent.com/55515949/87467343-a9250f80-c5cc-11ea-91b8-0d93bf330383.png)

I made the suggested improvements and tried to make the routing as short as I could. As far as the IMU, since that's being mounted onto the tibia, should I change the footprint? The pins shouldn't need to be as spaced out, right?

**Comment by Scharzenberger** [comment]
Hey Reyna,

Looks better.  You are right about the IMU, it will be mounted to the tibia.  Only wires will come back to the board, so you could use more screw terminals for that.

Is this a conflict?  It kind of looks like the wires are crossing...

![Inked87467343-a9250f80-c5cc-11ea-91b8-0d93bf330383_LI](https://user-images.githubusercontent.com/57116010/87473441-50f30b00-c5d6-11ea-80b6-dfe5d1583b1e.jpg)

Also, this looks like maybe a conflict?  Not sure...

![Inked87467343-a9250f80-c5cc-11ea-91b8-0d93bf330383_LI](https://user-images.githubusercontent.com/57116010/87473675-ae875780-c5d6-11ea-824c-2a15fa663877.jpg)

**Comment by Reyna-5970** [comment]
Whoops, I'll fix those things! I was dragging around the wires a bit so that's why that happened. I'll also change the IMU wiring to screw terminals.

**Comment by Reyna-5970** [comment]
![image](https://user-images.githubusercontent.com/55515949/87488515-75121480-c5f5-11ea-8d09-638d632dde04.png)
Changed the IMU input to screw terminal and fixed intersecting wires. If I dimension the PCB as such then will the holes that are going off of the board be an issue in manufacturing? This is more of an Eagle CAD specific question @Scharzenberger

**Comment by Reyna-5970** [comment]
Also, noticed that the wrong pin was square on the pressure sensor footprints so I changed that.

**Comment by Reyna-5970** [comment]
![image](https://user-images.githubusercontent.com/55515949/87593700-b7446000-c6a0-11ea-836a-114f2616bb1b.png)
Some of the text looks like it's overlapping but it shouldn't be. I added the text I want printed to the silkscreen layer "tPlane" and I believe the other text is just placed from before (when the devices were created for the schematic). I fixed the encoder wiring to go to interruptible pins: 2, 3, 18. I also added a ground plane.

**Comment by jakechung42** [comment]
Do you have a schematic view of the wiring similarly to this for the new design?
![image](https://user-images.githubusercontent.com/33278786/87600991-16a66e00-c6a9-11ea-9cf2-7560b1db2d07.png)
It's quite hard looking at the PCB wiring with all the labels like this. Thank you.

**Comment by Reyna-5970** [comment]
![image](https://user-images.githubusercontent.com/55515949/87601218-7f8de600-c6a9-11ea-9186-8bf28233c14e.png)

**Comment by jakechung42** [comment]
The wiring looks good. I don't know if Cody wants to add anything else.

**Comment by Scharzenberger** [comment]
Hey Reyna, it looks pretty good.  Glad you got the ground plane to work!  I think the wiring looks correct.

You have probably already tried messing with it, but you should be able to go in and move around, rotate, scale, etc all of the silk screen text.  Making some of it a bit smaller would probably help fitting it all on the board (since right now a lot of it is over lapping).  You only really need to label spots where there are connections to the board (like the screw terminals.  You don't really need to label the pins that are only internal to the board, because presumably, that will all be set up correctly and the user (e.g., you or us) won't have to worry about that at assembly time.  I would definitely leave the device names though.  If you can find the part number for the transistor array, it would probably be good to include that.  Same thing for the part number of the pressure sensors.

Now that it is mostly together, you can go to Osh park's website and see how much it will cost to make (but don't buy it yet -- you will need the lab's account info anyway): [https://oshpark.com/](https://oshpark.com/).  Their website walks you through it if I remember correctly.  Also, it will show you what the board will look like and tell you if it thinks there are problems with your file.

Good luck!  Let me know if you have any problems.

**Comment by Reyna-5970** [comment]
![image](https://user-images.githubusercontent.com/55515949/87974135-6eb0ec00-ca7e-11ea-8c11-3b8a86da91a0.png)
Is this okay? @Scharzenberger

**Comment by Reyna-5970** [comment]
![image](https://user-images.githubusercontent.com/55515949/88230427-44e6f900-cc27-11ea-8a5b-82136694f586.png)
I increased the width of the 24V wire. Plus, I added on a spot for this [MicroSD Adapter](https://www.adafruit.com/product/254) to plug-in to the shield.

I still need to look into how to remove the extra holes, but otherwise this is just an update about what I've done so far.

**Comment by Reyna-5970** [comment]
Also, the resistor connected to Pin 9 is supposed to be a pull-up resistor for the CD pin.

**Comment by Reyna-5970** [comment]
Another update: found [this link](https://learn.sparkfun.com/tutorials/pull-up-resistors) explaining more about pull-up resistors so I fixed the wiring on that. Looks like we don't necessarily need to use the CD pin because it's just to detect whether there's a SD card actually plugged in or not, but just in case, I thought I'd include the wiring to be ready.

**Comment by Reyna-5970** [comment]
![image](https://user-images.githubusercontent.com/55515949/88241433-f04f7800-cc3e-11ea-8f3c-a803d83141b2.png)
